name: Run Tests
on:
 push:
jobs:
 test:
  runs-on:ubuntu-latest
  steps:
   - name: Set up JDR
     uses: actions/setup-java@v2
     with:
      distribution: 'adopt'
      java-version: '11'
  - name: Check out code
    uses:actions/checkout@v2
  - name: Build and test
    run: ./gradlew test
